# Generated by Django 5.1.6 on 2025-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_loancalculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancalculation',
            old_name='amount',
            new_name='resultado',
        ),
        migrations.RemoveField(
            model_name='loancalculation',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loancalculation',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='loancalculation',
            name='term_months',
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='calculation_subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='calculation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='gracia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='periodos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='renta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='vf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loancalculation',
            name='vp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
